// Mocks generated by Mockito 5.1.0 from annotations
// in flutter_architecture/test/home/domain/home_page_usecase_test.dart.
// Do not manually edit this file.

import 'package:flutter_architecture/data/data_source/remote/apis.dart' as _i3;
import 'package:flutter_architecture/data/setting/repositories/setting_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [SettingRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingRepository extends _i1.Mock implements _i2.SettingRepository {
  MockSettingRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set api(_i3.Apis? _api) => super.noSuchMethod(Invocation.setter(#api, _api),
      returnValueForMissingStub: null);
}
